### ISSUE TITLE
Error Messages on Install

### ISSUE THREAD

**Issue by peerzombie** [shagabutdinov/sublime-enhanced#2]
So ive stumbled across this plugin(-collection) and thought "heck lets try itout". I followed the instructions step by step. Now, after i restarted Sublime Text i got these 4 errors:
![Error 1] (http://s5.postimg.org/kz02lrxmf/error1.png)
![Error 2] (http://s5.postimg.org/7jd1wbp4n/error2.png)
![Error 3] (http://s5.postimg.org/4rts5pqlz/error3.png)
![Error 4] (http://s5.postimg.org/fddnhpwxj/error4.png)
Due to an Error in package control (it loads infinitly after installing an custom package) im unable to (try and) fix it over that.

Any ideas ?

**Comment by shagabutdinov** [comment]
Did you install all plugins one by one through package manager or you cloned it through the git to packages folder?

**Comment by peerzombie** [comment]
I actually did clone it with git:
Steps: 
1) Move to `C:\Program Files (x86)\Git` and run `Git Bash.vbs`
2) executed command cd `~/AppData/Roaming/Sublime\ Text\ 3/Packages`
3) Copyed the WHOLE block of `git clone xx xx` from [the Readme] (https://github.com/shagabutdinov/sublime-enhanced/blob/master/readme-installation.md).
4) Pasted it into the Console
5) Let it all execute.
6) Pressed Enter one more Time (to execute the last one)
7) Followed step 4, 5 and 6 in [the Readme] (https://github.com/shagabutdinov/sublime-enhanced/blob/master/readme-installation.md).
8) Restarted Sublime Text 3

**Comment by shagabutdinov** [comment]
I think the manual become outdated after guys from `packagecontrol.io` forced me to rename a particular plugins in order to release them in their system. 

Instructions for each notice:

1. Just remove `TerminalProjectFolder`, you don't need it because you don't have `sublime_terminal` plugin; or install `sublime_terminal` plugin (https://github.com/wbond/sublime_terminal)

2. For other notices: I'm not sure what can go wrong; could you please try to change the block:

```
try:
  from Expression import expression
except ImportError:
  sublime.error_message("Dependency import failed; please read readme for " +
   "Statement plugin for installation instructions; to disable this " +
   "message remove this plugin")
```

to:

```
from Expression import expression
```

in file Statement/statement.py

and show me the console output? Thank you in advance.

**Comment by peerzombie** [comment]
So i have Some Solutions.
1) Downloading sublime_terminal into Terminal did the trick for Error 1
2) I did as you said. The Result where only 2 errors (FolderFiles and Autocompletion). I posted the log [on Pastebin] (http://pastebin.com/qVERzM9D) due to its length.
EDIT:
I was able to Import all dependencys for the FolderFiles Plugin. The only Error i have is the one With Autocomplete.
For (eventual) debug purposes you can find the Folderlist of the `Packages` dir [here] (http://pastebin.com/ds7pzHmA)

**Comment by shagabutdinov** [comment]
Please, remove indentation before (this is python feature: indentation are affects code execution):

```
    from Statement import statement
    from Expression import expression
```

You seems to be second person after me who installs full stack of this plugins and have strong intention to use it =) We should work more closely. I didn't debug whole installation because nobody used it that is why it works so awful. I will try to respond faster to your messages for next times.

**Comment by peerzombie** [comment]
1) I'm programming myself and i know a little python
2) Where do i replace these ? (Wich file & Plugin) because i can't find in in FolderFiles nor in Autocomplete.
>`from Statement import statement
>
> from Expression import expression`
3) Yea, i saw this and i thought "Heck, wy not, maybe it helps" :smile:

**Comment by shagabutdinov** [comment]
I believe it is in `C:\Users\TheLazyAdmin\AppData\Roaming\Sublime Text 3\Packages\Statement\statement.py`.

Also `Autocompletion` should be renamed to `AutocompletionFuzzy`.

**Comment by peerzombie** [comment]
So... I (tried) to do as you Said... this is the current content of [statement.py](http://pastebin.com/v61kVPj4). The renaming of `Autocompletion` to `AutocompletionFuzzy` did the trick.
My Problem is now: I cant seem to find the line `from Statement import statement`. if i add it manually on line 9 i get around 30 Errors: [The Log] (http://pastebin.com/2ei1btpZ).

**Comment by bzkdjc** [comment]
Here also: "Error messages on Install" 

Someone tried install on a fresh Ubuntu Wily (15.10) ?? 
Just tried, but keep getting following error for each line of step 3: 
```
Please make sure you have the correct access rights
and the repository exists.
Cloning into 'AlignCursors'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```
Got 53 of that same message!

Is authentication differently handled on those repos?
```
git clone git@github.com:shagabutdinov/sublime-align-cursors.git AlignCursors...
```

**Comment by peerzombie** [comment]
when youre in an git shell (PowerShell/Cmd/Terminal with git activated) it should work, also, please open this in an (kind of) new thread or ask in an github forum (this thread is related to an differen error of mine)

**Comment by shagabutdinov** [comment]
> So... I (tried) to do as you Said... this is the current content of statement.py. The renaming of Autocompletion to AutocompletionFuzzy did the trick.

Seems you did very wrong modifications because `Statement` wants to import itself now:

```
  File "C:\Users\TheLazyAdmin\AppData\Roaming\Sublime Text 3\Packages\Statement\statement.py", line 9, in <module>
    from Statement import statement
```

I've updated all plugins and added correct error message, could you please reinstall all plugins and show exception again?

**Comment by shagabutdinov** [comment]
> Here also: "Error messages on Install"

Please move your messages to separate issue and I'll reply to you. It is very bad point to discuss different issues in one thread. Thank you.

**Comment by peerzombie** [comment]
@shagabutdinov so i did as you saind (reinstalled everything, added the fix for Autocompletion (appended Fuzzy to the end of the name) )
Now i get these two errors:
![error5] (http://s21.postimg.org/6bibygd47/error5.png)
![error6] (http://s21.postimg.org/6bibygd47/error5.png)
Again, i posted the log on [Pastebin.com] (http://pastebin.com/y5bPmHgZ)

**Comment by shagabutdinov** [comment]
Ok, great, this helped a lot! Please, update `Semicolon` plugin (I made
changes here) and try to install `OpenPath` (`sublime-open-path`) plugin -
for some reason sublime does not see it.


--
Leonid Shagabutdinov,
+7 905 937 6988

**Comment by peerzombie** [comment]
So, i did as you said. FIrst time i launched SublimeText3 it did all go smoothly (no errors, everything worked) but then i closed sumlime text and reopened it (due to an suspicion i had) and i found out: on start, sublime text removes the OpenPath folder from the File system. I think i fixed it throu disallowing myself to write into content of the folder. Do you know wy this is happening (besides that everything works)

**Comment by shagabutdinov** [comment]
I think there is problem with sublime package manager; could you please disable it or try to remove OpenPath from "Installed Packages" folder?

**Comment by peerzombie** [comment]
Okay, that solved it.

Now Everything is funktional and with this i declare this issue as solved !

Thanks a lot !

**Comment by shagabutdinov** [comment]
No problem =) Let me know if you need any another help.
