### ISSUE TITLE
Problem with command 'git clone'

### ISSUE THREAD

**Issue by bzkdjc** [shagabutdinov/sublime-enhanced#3]
I want to try `sublime-enhanced`. 
When I execute commands from step 3 (_`git clone git@github.com:shagabutdinov/sublime-align-cursors.git AlignCursors...`_) using `bash` under Ubuntu, I keep getting: 
```
Please make sure you have the correct access rights
and the repository exists.
Cloning into 'AlignCursors'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```
I get 53 of that same message!

**Comment by shagabutdinov** [comment]
You should add your public key to github:
https://help.github.com/articles/generating-ssh-keys/


--
Leonid Shagabutdinov, CTO
idfly.ru, +7 905 937 6988
