### ISSUE TITLE
Create Sublime Package

### ISSUE THREAD

**Issue by nigurr** [shagabutdinov/sublime-enhanced#5]
Hi,

It would be great, if you can create Sublime Package and submit to package system. 
Installation/Upgrade would be easier

**Comment by shagabutdinov** [comment]
Sublime Enhanced is plugin set, not a single package: 

* It is designed to be a set of different packages 
* `sublime package control` itself does not provide a way to install several packages at once
* Also, sometimes behaviour changes in an unexpected way (there is why `sublime_enhanced_keybindings`) so by installing all packages at once user will not be available to disable the plugin he didn't like
